INSERT INTO songs (name, albums_id, length_seconds, genre) VALUES 
('Blank Space', 1, 231, 'Pop'),
('Style', 1, 231, 'Pop'),
('Wildest Dreams', 1, 220, 'Pop'),
('Anti-Hero', 2, 200, 'Pop'),
('Lavender Haze', 2, 202, 'Electronic'),
('Snow on the Beach', 2, 256, 'Pop'),
('Shape of You', 3, 233, 'Pop'),
('Perfect', 3, 263, 'Pop'),
('Galway Girl', 3, 170, 'Folk'),
('Bad Habits', 4, 231, 'Electronic'),
('Shivers', 4, 207, 'Pop'),
('Whenever, Wherever', 5, 195, 'Latin Pop'),
('Underneath Your Clothes', 5, 223, 'Pop'),
('Chantaje', 6, 195, 'Reggaeton'),
('La Bicicleta', 6, 229, 'Latin Pop'),
('Because You Loved Me', 7, 240, 'Pop'),
('It''s All Coming Back to Me Now', 7, 330, 'Ballad'),
('A New Day Has Come', 7, 240, 'Pop'),
('I''m Alive', 7, 210, 'Pop'),
('Smooth Jazz Moment', 2, 300, 'Jazz'),
('Electric Dreams', 4, 215, 'Electronic');